# What Is NumPy?

In Python, a collection is often stored using the list data type. A Python list is conceptually similar to arrays in languages such as Java, C#, and JavaScript. The following code example shows a Python list:

In [3]:
list1 = [1, 2, 3, 4, 5]
print("List 1 output: ", list1)

List 1 output:  [1, 2, 3, 4, 5]


Unlike arrays, a Python list does not need to contain elements of the same type. The following example is a perfectly valid list in Python:

In [6]:
list2 = [1, "Hello", 3.14, 5]
print("list 2 outputs: ")
for i in list2:
    print(i)

list 2 outputs: 
1
Hello
3.14
5


This unique feature in Python provides flexibility when handling multiple data types within a list, but it also has disadvantages when processing large amounts of data, as is typically the case in machine learning and data science projects. The main issue with Python's list data type is efficiency. To allow elements of different types in a list, each item in the list is stored in a separate memory location, and the list contains an "array" of pointers to each of these locations.

A Python list requires the following:

- At least 4 bytes per pointer.

- Even the smallest Python object consists of at least 16 bytes: 4 bytes for a pointer, 4 bytes for a reference count, and 4 bytes for a value. Altogether, these add up to 16 bytes.

## Extending Python with NumPy

Because of the way a Python list is implemented, accessing elements in a large list is computationally expensive. To address this limitation of Python lists, Python programmers turn to NumPy, which is an extension to the Python programming language that adds support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.

In NumPy, an array is of type ndarray (n-dimensional array), and all elements must be of the same type. An ndarray object represents a multi-dimensional, homogeneous array of fixed-size items and is much more efficient than Python's built-in list. The ndarray object also provides functions that perform operations on the entire array.


## Creating NumPy Arrays

Before using NumPy, you first need to import the NumPy package (you may use the alias np if you prefer):

In [11]:
import numpy as np

The first way to create NumPy arrays is by using the built-in functions provided directly by NumPy. First, you can use the arange() function to create an evenly spaced array within a specified range:

In [14]:
a1 = np.arange(10)
print("a1: ",a1)
print(a1.shape)

a1:  [0 1 2 3 4 5 6 7 8 9]
(10,)


he expression above creates a rank-1 array (one-dimensional) with ten elements. Use the shape attribute to get the shape of the array. You can think of a1 as a 10 × 1 matrix.

You can also specify a step value in the arange() function. The following code example adds a step value of 2:

In [17]:
a2 = np.arange(0,10,2)
print("a2: ",a2)

a2:  [0 2 4 6 8]


Use the zeros() function to create an array of a specified size consisting entirely of zeros:

In [20]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


You can also create two-dimensional arrays using the zeros() function:

In [23]:
a4 = np.zeros((2,3))
print(a4.shape)
print(a4)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


If you want an array filled with a specific value instead of 0, use the full() function:

In [26]:
a5 = np.full((2,3),8)
print(a5)

[[8 8 8]
 [8 8 8]]


Sometimes, you may need to create an array that represents an identity matrix. In NumPy, you can do this by using the eye() function:

In [29]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


The eye() function returns a two-dimensional array with ones on the diagonal and zeros elsewhere.

To create an array filled with random numbers, you can use the random() function from the numpy.random module:

In [32]:
a7 = np.random.random((2,4))
print(a7)

[[0.96032722 0.33620775 0.23244266 0.90491337]
 [0.00704534 0.50744667 0.74624349 0.68220676]]


Another way to create a NumPy array is from a Python list, as shown below:

In [35]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


##  Array Indexing

Accessing elements in an array is similar to accessing elements in a Python list:

In [39]:
print(r1[0])
print(r1[1])

1
2


The following code snippet creates another array named r2, which is two-dimensional:

In [42]:
list2 = [6, 7, 8, 9, 0]
r2 = np.array([list1, list2])
print(r2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [44]:
print(r2.shape)
print(r2[0,0])
print(r2[0,1])
print(r2[1,0])

(2, 5)
1
2
6


Here, r2 is a rank-2 array with two rows and five columns.

In addition to using a single index to access elements in an array, you can also use a list as an index:

In [47]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1[[2,4]])

[3 5]


## Boolean Indexing

In addition to using indexing to access elements in an array, there is another very useful way to access elements in a NumPy array. Consider the following:

In [51]:
print(r1 > 2)

[False False  True  True  True]


This expression prints a list containing Boolean values. What it actually does is check each element in r1 and determine whether each element is greater than two. The result is a Boolean value for each element, and at the end of the operation, a list of Boolean values is created. You can then pass the list result back into the array:

In [54]:
print(r1[r1 > 2])

[3 4 5]


This method of accessing elements in an array is called Boolean Indexing. This method is very useful. Consider the following example:

In [57]:
nums = np.arange(20)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


If you want to get all the odd numbers in the list, you can simply use Boolean Indexing as follows:

In [60]:
odd_num = nums[nums % 2 == 1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


## Array Slicing

Slicing in NumPy arrays works similarly to how it works in a Python list. Consider the following example:

In [64]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [9,8,7,6,5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


You can use slicing to extract the last two rows and the first two columns:

In [67]:
b1 = a[1:3, :3]
print("The code snippet above will print the following:: ")
print(b1)

The code snippet above will print the following:: 
[[4 5 6]
 [9 8 7]]


Let us examine this code. Slicing has the following syntax: [start:end]. For two-dimensional arrays, the slicing syntax takes the form [start:end, start:end]. The start:end part before the comma refers to the rows, while the start:end part after the comma refers to the columns. Therefore, in [1:3, :3], you are specifying that you want to extract the rows with indices from 1 up to 3 (excluding 3), and the columns starting from the first column up to index 3 (excluding 3). A common source of confusion in slicing is the end index. You need to remember that the end index is not included in the result. To visualize slicing more clearly, it is better to think of the indices as being placed between the numbers, rather than in the middle of them.

Using this approach, it becomes much easier to understand how slicing works.

What about negative indices? For example, consider the following:

In [70]:
b2 = a[-2:, -2:]
print(b2)

[[7 8]
 [6 5]]


## NumPy Slicing Is a Reference

It is important to note that the result of NumPy slicing is a reference, not a copy of the original array. Consider the following:

In [74]:
b3 = a[1:, 2:]
print("The result is as follows: \n")
print(b3)

The result is as follows: 

[[6 7 8]
 [7 6 5]]


Here, b3 is actually a reference to the original array a. Therefore, if you modify one of the elements in b3 as follows:

In [77]:
b3[0,2] = 88
print("The result will affect the contents of a as follows: \n")
print(a)

The result will affect the contents of a as follows: 

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


It is important to remember that the result of slicing can vary depending on how you perform the slicing.

Here is an example:

In [80]:
b4 = a[2:, :]
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


In the expression above, you are selecting the rows with index 2 and above, along with all columns. The result will be a rank-2 array as follows:

In [83]:
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


If you have an operation like the following:

In [86]:
b5 = a[2, :]
print(b5)

[9 8 7 6 5]


the result will be a rank-1 array:

In [89]:
print(b5)

[9 8 7 6 5]


Printing the shape of the array confirms this:

In [92]:
print(b5.shape)

(5,)


##  Reshaping Arrays

You can reshape an array into another dimension by using the reshape() function. Using the example of b5, which is a rank-1 array, you can reshape it into a rank-2 array as follows:

In [96]:
b5 = b5.reshape(1, -1)
print(b5)

[[9 8 7 6 5]]


In this example, you are calling the reshape() function with two arguments. The first, 1, indicates that you want to convert it into a rank-2 array with one row, and -1 tells the reshape() function to determine the correct number of columns automatically. Of course, in this example, it is clear that there will be five columns after reshaping, so you could also call the function as reshape(1, 5). However, in more complex cases, it is always useful to be able to use -1 to let the function determine the number of rows or columns to be created.

Here is another example showing how to reshape b4 (which is a rank-2 array) into a rank-1 array:

In [99]:
print(b4.reshape(-1,))

[9 8 7 6 5]


-1 indicates that you are allowing the function to decide how many rows to create, as long as the result is a rank-1 array.

Tip: To convert a rank-2 array into a rank-1 array, you can also use the flatten() or ravel() functions. The flatten() function always returns a copy of the array, whereas the ravel() and reshape() functions return a view (reference) of the original array.

## Array Mathematics

You can perform array mathematics on NumPy arrays very easily. Consider the following two rank-2 arrays:

In [104]:
x1 = np.array([[1,2,3], [4,5,6]])
y1 = np.array([[7,8,9], [2,3,4]])

To add these two arrays together, use the + operator:

In [107]:
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


The result is the sum of each corresponding element in the two arrays:

In [110]:
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


Array mathematics is important because it can be used to perform vector calculations. A good example is as follows:

In [113]:
x = np.array([2,3])
y = np.array([4,2])
z = x + y
print(z)

[6 5]


Figure 2.5 shows the use of arrays to represent vectors and uses array addition to perform vector summation. In addition to using the + operator, you can also use the np.add() function to add two arrays:

In [116]:
print(np.add(x1, y1))

[[ 8 10 12]
 [ 6  8 10]]


In addition to addition, you can also perform subtraction, multiplication, and division with NumPy arrays:

In [119]:
print("Result of the operation x1 - y1 : \n", (x1 - y1),"\n")
print("Result of the operation x1 * y1 : \n", (x1 * y1),"\n")
print("Result of the operation x1 / y1 : \n", (x1 / y1),"\n")


Result of the operation x1 - y1 : 
 [[-6 -6 -6]
 [ 2  2  2]] 

Result of the operation x1 * y1 : 
 [[ 7 16 27]
 [ 8 15 24]] 

Result of the operation x1 / y1 : 
 [[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]] 



What is a practical use of multiplying or dividing two arrays?

For example, suppose you have three arrays:

One contains the names of a group of people,

Another contains the corresponding heights of these individuals, and the last one contains the corresponding weights of the individuals in the group:

In [122]:
names = np.array(["Ann", "Joe", "Mark"])
heights = np.array([1.5, 1.76, 1.6])
weights = np.array([65, 46, 59])

Now suppose you want to calculate the Body Mass Index (BMI) of this group of people. The formula used to calculate BMI is as follows:

Divide the weight in kilograms (kg) by the height in meters squared,

Then divide the resulting value by the height once again

Using BMI, you can classify a person as underweight, overweight, or healthy:

If BMI < 18.5, the person is underweight,

If BMI > 25, the person is overweight,

If 18.5 <= BMI <= 25, the person has a normal weight

By using array division, you can simply calculate BMI with the following expression:

In [125]:
bmi = weights / heights ** 2
print(bmi)

[28.88888889 14.85020661 23.046875  ]


Now it is very easy to determine who is overweight, underweight, or in the normal category:

In [128]:
print("Overweight: ", names[bmi > 25])
print("Underweight: ", names[bmi < 18.5])
print("Healthy: ", names[(bmi >= 18.5) &(bmi <= 25)])

Overweight:  ['Ann']
Underweight:  ['Joe']
Healthy:  ['Mark']


## Dot Product

When you multiply two arrays, you are actually multiplying the corresponding elements in the two arrays. Very often, however, you may want to perform a scalar product, also known as a dot product. The dot product is an algebraic operation that takes two coordinate vectors of equal size and returns a single number. The dot product of two vectors is calculated by multiplying the corresponding entries in each vector and then summing all of these products. For example, given two vectors — a = [a1, a2, . . ., an] and b = [b1, b2, . . ., bn] — the dot product of these two vectors is a1b1 + a2b2 + . . . + anbn.

In NumPy, the dot product is performed using the dot() function:

In [132]:
x = np.array([2,3]) 
y = np.array([4,2]) 
print(np.dot(x,y))

14


The dot product also works with rank-2 arrays. If you take the dot product of two rank-2 arrays, it is equivalent to the following matrix multiplication:

In [135]:
x2 = np.array([[1,2,3],[4,5,6]]) 
y2 = np.array([[7,8],[9,10], [11,12]]) 
print(np.dot(x2,y2))

[[ 58  64]
 [139 154]]


Figure 2.6 illustrates how matrix multiplication works. The first result, 58, is obtained from the dot product of the first row of the first array and the first column of the second array — 1 × 7 + 2 × 9 + 3 × 11 = 58. The second result, 64, is obtained from the dot product of the first row of the first array and the second column of the second array — 1 × 8 + 2 × 10 + 3 × 12 = 64. And so on.

## Matrices

NumPy provides another class in addition to arrays (ndarray): the matrix. The matrix class is a subclass of ndarray and is essentially the same as an ndarray, but with one important difference—a matrix is strictly two-dimensional, whereas an ndarray can be multi-dimensional. Creating a matrix object is similar to creating a NumPy array:

In [140]:
x2 = np.matrix([[1,2],[4,5]]) 
y2 = np.matrix([[7,8],[2,3]]) 

ou can also convert a NumPy array to a matrix by using the asmatrix() function:

In [143]:
x1 = np.array([[1,2],[4,5]]) 
y1 = np.array([[7,8],[2,3]]) 
x1 = np.asmatrix(x1) 
y1 = np.asmatrix(y1)

Another important difference between an ndarray and a matrix appears when multiplication is performed on them. When you multiply two ndarray objects, the result is the element-wise multiplication we saw earlier. On the other hand, when you multiply two matrix objects, the result is the dot product (equivalent to the np.dot() function):

In [146]:
x1 = np.array([[1,2],[4,5]]) 
y1 = np.array([[7,8],[2,3]]) 
print("Result of the operation x1 * y1 : \n", (x1 * y1), "\n")
x2 = np.matrix([[1,2],[4,5]]) 
y2 = np.matrix([[7,8],[2,3]]) 
print("Result of the operation x2 * y2 : \n", (x2 * y2), "\n")

Result of the operation x1 * y1 : 
 [[ 7 16]
 [ 8 15]] 

Result of the operation x2 * y2 : 
 [[11 14]
 [38 47]] 



## Cumulative Sum

When working with numerical data, it is often necessary to find the cumulative sum of the numbers in a NumPy array. Consider the following array:

In [150]:
a = np.array([(1,2,3),(4,5,6), (7,8,9)]) 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


You can call the cumsum() function to obtain the cumulative sum of the elements:

print(a.cumsum())

In this case, the cumsum() function returns a rank-1 array containing the cumulative sum of all elements in array a. The cumsum() function also takes an optional argument — axis. Specifying the axis value as 0 indicates that you want to obtain the cumulative sum of each column:

In [155]:
print(a.cumsum(axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


Specifying the axis value as 1 indicates that you want to obtain the cumulative sum of each row:

In [158]:
print(a.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


Figure 2.7 makes it easier to understand how the axis parameter affects the way cumulative sums are obtained.

## NumPy Sorting

NumPy provides a number of efficient sorting functions that make it very easy to sort an array. The first function for sorting is the sort() function, which takes an array and returns a sorted array. Consider the following example:

In [163]:
ages = np.array([34,12,37,5,13]) 
sorted_ages = np.sort(ages)
print(sorted_ages)
print(ages)

[ 5 12 13 34 37]
[34 12 37  5 13]


As you can see from the output, the sort() function does not modify the original array. Instead, it returns a sorted array. If you want to sort the original array itself, call the sort() function on the array directly, as follows:

In [166]:
ages.sort()
print(ages)

[ 5 12 13 34 37]


Another function used for sorting is the argsort() function. To understand how it works, it is helpful to examine the following code example:

In [169]:
ages = np.array([34,12,37,5,13]) 
print(ages.argsort())

[3 1 4 0 2]


The argsort() function returns the indices that would be used to sort an array. In the previous example, the first element in the result of the argsort() function, (3), indicates that after sorting, the smallest element is located at index 3 in the original array, which is the value 5. The next number is at index 1, which is the value 12, and so on. Figure 2.8 shows the meaning of the sorting indices.

To print the sorted age array, use the result of the argsort() function as an index for the age array:

In [172]:
print(ages[ages.argsort()])

[ 5 12 13 34 37]


What is the actual use of argsort()? Imagine that you have a list of people represented by three arrays containing their ages and heights:

In [175]:
persons = np.array(['Johnny','Mary','Peter','Will','Joe']) 
ages = np.array([34,12,37,5,13]) 
heights = np.array([1.76,1.2,1.68,0.5,1.25])

Suppose you want to sort this group of people by age. If you sort only the age array, the other two arrays will not be sorted correctly according to age. This is where argsort() becomes truly useful:

In [178]:
sort_indices = np.argsort(ages)

Once the sorting indices have been obtained, simply apply these indices to all three arrays:

In [181]:
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


Now they are sorted by age. As you can see, Will is the youngest, Mary follows, and so on. The corresponding height for each person will also be in the correct order.

If you want to sort by name, simply use the argsort() function on the persons array and apply the resulting indices to all three arrays:

In [184]:
sort_indices = np.argsort(persons)
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])

['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
[13 34 12 37  5]
[1.25 1.76 1.2  1.68 0.5 ]


## Array Assignment

When assigning NumPy arrays, you need to pay attention to how the arrays are assigned. Below are several examples to explain this concept.

Copying by Reference

Consider an array a1:

In [188]:
list1 = [[1,2,3,4], [5,6,7,8]] 
a1 = np.array(list1) 
print(a1) 

[[1 2 3 4]
 [5 6 7 8]]


When you try to assign a1 to another variable, a2, a reference copy of the array is created:

In [191]:
a2 = a1
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

a1:  [[1 2 3 4]
 [5 6 7 8]] 

a2:  [[1 2 3 4]
 [5 6 7 8]] 



However, a2 actually points to the original a1. Therefore, changes made to either array will affect the other:

In [194]:
a2[0][0] = 11
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

a1:  [[11  2  3  4]
 [ 5  6  7  8]] 

a2:  [[11  2  3  4]
 [ 5  6  7  8]] 



Tip: In the “Reshaping Arrays” section of this chapter, we saw how to change the shape of an ndarray using the reshape() function. In addition to using the reshape() function, you can also change its dimensions by using the shape attribute of the ndarray.

If the shape of a1 changes, a2 will also be affected as follows:

In [197]:
a1.shape = 1,-1
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

a1:  [[11  2  3  4  5  6  7  8]] 

a2:  [[11  2  3  4  5  6  7  8]] 



## Copying with a View (Shallow Copy)

NumPy provides the view() function to copy an array by reference. At the same time, it ensures that changing the shape of the original array does not affect the shape of the copy. This is called a shallow copy. To understand how this works, let us look at an example:

In [201]:
a2 = a1.view()
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

a1:  [[11  2  3  4  5  6  7  8]] 

a2:  [[11  2  3  4  5  6  7  8]] 



Traditionally, if you change a value in a1, you will see the changes in a2:

In [204]:
a1[0][0] = 11
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

a1:  [[11  2  3  4  5  6  7  8]] 

a2:  [[11  2  3  4  5  6  7  8]] 



So far, a shallow copy is the same as the copying performed in the previous section. However, with a shallow copy, when you change the shape of a1, a2 is not affected:

In [207]:
a1.shape = 1,-1
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

a1:  [[11  2  3  4  5  6  7  8]] 

a2:  [[11  2  3  4  5  6  7  8]] 



## Copying by Value (Deep Copy)

If you want to copy an array by value, use the copy() function, as shown in the following example:

In [211]:
list1 = [[1,2,3,4], [5,6,7,8]] 
a1 = np.array(list1)
a2 = a1.copy()

The copy() function creates a deep copy of the array — it creates a complete copy of both the array and its data. When you assign the copy to another variable, changes made to the shape of the original array do not affect the copy. Here is the proof:

In [214]:
print("Result of the operation a1[0][0] = 11 : \n")
a1[0][0] = 11
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n") 

print("--- \n")

print("Result of the operation a1.shape = 1,-1 : \n")
a1.shape = 1,-1
print("a1: ", a1, "\n") 
print("a2: ", a2, "\n")

Result of the operation a1[0][0] = 11 : 

a1:  [[11  2  3  4]
 [ 5  6  7  8]] 

a2:  [[1 2 3 4]
 [5 6 7 8]] 

--- 

Result of the operation a1.shape = 1,-1 : 

a1:  [[11  2  3  4  5  6  7  8]] 

a2:  [[1 2 3 4]
 [5 6 7 8]] 

